In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [15]:
daily1 = pd.read_csv('data/mturkfitbit_export_4.12.16-5.12.16/Fitabase data 4.12.16-5.12.16/dailyActivity_merged.csv')
daily2 = pd.read_csv('data/mturkfitbit_export_4.12.16-5.12.16/Fitabase data 4.12.16-5.12.16/dailyCalories_merged.csv')
daily3 = pd.read_csv('data/mturkfitbit_export_4.12.16-5.12.16/Fitabase data 4.12.16-5.12.16/dailyIntensities_merged.csv')
daily4 = pd.read_csv('data/mturkfitbit_export_4.12.16-5.12.16/Fitabase data 4.12.16-5.12.16/dailySteps_merged.csv')
heartrate_seconds_merged = pd.read_csv('data/mturkfitbit_export_4.12.16-5.12.16/Fitabase data 4.12.16-5.12.16/heartrate_seconds_merged.csv')

In [23]:
file_groups = {
    "daily": ["dailyActivity_merged.csv", "dailyCalories_merged.csv", "dailyIntensities_merged.csv", "dailySteps_merged.csv"],
    "hourly": ["hourlyCalories_merged.csv", "hourlyIntensities_merged.csv", "hourlySteps_merged.csv"],
    "minute": ["minuteCaloriesNarrow_merged.csv", "minuteCaloriesWide_merged.csv", "minuteIntensitiesNarrow_merged.csv", "minuteIntensitiesWide_merged.csv", "minuteMETsNarrow_merged.csv", "minuteSleep_merged.csv", "minuteStepsNarrow_merged.csv", "minuteStepsWide_merged.csv"],
    "info": ["heartrate_seconds_merged.csv", "sleepDay_merged.csv", "weightLogInfo_merged.csv"]
}

data = {}
for group, files in file_groups.items():
    data[group] = {
    f.replace("_merged.csv", ""): pd.read_csv(os.path.join('data/mturkfitbit_export_4.12.16-5.12.16/Fitabase data 4.12.16-5.12.16', f))
    for f in files
    }

In [22]:
data['daily']['dailyActivity '].head()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,4/12/2016,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,25,13,328,728,1985
1,1503960366,4/13/2016,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,21,19,217,776,1797
2,1503960366,4/14/2016,10460,6.74,6.74,0.0,2.44,0.40,3.91,0.0,30,11,181,1218,1776
3,1503960366,4/15/2016,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.0,29,34,209,726,1745
4,1503960366,4/16/2016,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.0,36,10,221,773,1863

In [31]:
for group, frame in data.items() :
    print(f"\n========{group.upper()}===========")
    for name, df in frame.items(): 
        print(f"\n------{name}-------")
        display(df.head())

========DAILY===========

------dailyActivity-------

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,4/12/2016,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,25,13,328,728,1985
1,1503960366,4/13/2016,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,21,19,217,776,1797
2,1503960366,4/14/2016,10460,6.74,6.74,0.0,2.44,0.40,3.91,0.0,30,11,181,1218,1776
3,1503960366,4/15/2016,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.0,29,34,209,726,1745
4,1503960366,4/16/2016,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.0,36,10,221,773,1863

------dailyCalories-------

           Id ActivityDay  Calories
0  1503960366   4/12/2016      1985
1  1503960366   4/13/2016      1797
2  1503960366   4/14/2016      1776
3  1503960366   4/15/2016      1745
4  1503960366   4/16/2016      1863

------dailyIntensities-------

,Id,ActivityDay,SedentaryMinutes,LightlyActiveMinutes,FairlyActiveMinutes,VeryActiveMinutes,SedentaryActiveDistance,LightActiveDistance,ModeratelyActiveDistance,VeryActiveDistance
0,1503960366,4/12/2016,728,328,13,25,0.0,6.06,0.55,1.88
1,1503960366,4/13/2016,776,217,19,21,0.0,4.71,0.69,1.57
2,1503960366,4/14/2016,1218,181,11,30,0.0,3.91,0.40,2.44
3,1503960366,4/15/2016,726,209,34,29,0.0,2.83,1.26,2.14
4,1503960366,4/16/2016,773,221,10,36,0.0,5.04,0.41,2.71

------dailySteps-------

           Id ActivityDay  StepTotal
0  1503960366   4/12/2016      13162
1  1503960366   4/13/2016      10735
2  1503960366   4/14/2016      10460
3  1503960366   4/15/2016       9762
4  1503960366   4/16/2016      12669

========HOURLY===========

------hourlyCalories-------

           Id           ActivityHour  Calories
0  1503960366  4/12/2016 12:00:00 AM        81
1  1503960366   4/12/2016 1:00:00 AM        61
2  1503960366   4/12/2016 2:00:00 AM        59
3  1503960366   4/12/2016 3:00:00 AM        47
4  1503960366   4/12/2016 4:00:00 AM        48

------hourlyIntensities-------

           Id           ActivityHour  TotalIntensity  AverageIntensity
0  1503960366  4/12/2016 12:00:00 AM              20          0.333333
1  1503960366   4/12/2016 1:00:00 AM               8          0.133333
2  1503960366   4/12/2016 2:00:00 AM               7          0.116667
3  1503960366   4/12/2016 3:00:00 AM               0          0.000000
4  1503960366   4/12/2016 4:00:00 AM               0          0.000000

------hourlySteps-------

           Id           ActivityHour  StepTotal
0  1503960366  4/12/2016 12:00:00 AM        373
1  1503960366   4/12/2016 1:00:00 AM        160
2  1503960366   4/12/2016 2:00:00 AM        151
3  1503960366   4/12/2016 3:00:00 AM          0
4  1503960366   4/12/2016 4:00:00 AM          0

========MINUTE===========

------minuteCaloriesNarrow-------

           Id         ActivityMinute  Calories
0  1503960366  4/12/2016 12:00:00 AM    0.7865
1  1503960366  4/12/2016 12:01:00 AM    0.7865
2  1503960366  4/12/2016 12:02:00 AM    0.7865
3  1503960366  4/12/2016 12:03:00 AM    0.7865
4  1503960366  4/12/2016 12:04:00 AM    0.7865

------minuteCaloriesWide-------

,Id,ActivityHour,Calories00,Calories01,Calories02,Calories03,Calories04,Calories05,Calories06,Calories07,...,Calories50,Calories51,Calories52,Calories53,Calories54,Calories55,Calories56,Calories57,Calories58,Calories59
0,1503960366,4/13/2016 12:00:00 AM,1.8876,2.2022,0.9438,0.9438,0.9438,2.0449,0.9438,2.2022,...,0.9438,2.0449,2.0449,0.9438,2.3595,1.8876,0.9438,0.9438,0.9438,0.9438
1,1503960366,4/13/2016 1:00:00 AM,0.7865,0.7865,0.7865,0.7865,0.9438,0.9438,0.9438,0.7865,...,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865
2,1503960366,4/13/2016 2:00:00 AM,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,...,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865
3,1503960366,4/13/2016 3:00:00 AM,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,...,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865
4,1503960366,4/13/2016 4:00:00 AM,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,...,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865

------minuteIntensitiesNarrow-------

           Id         ActivityMinute  Intensity
0  1503960366  4/12/2016 12:00:00 AM          0
1  1503960366  4/12/2016 12:01:00 AM          0
2  1503960366  4/12/2016 12:02:00 AM          0
3  1503960366  4/12/2016 12:03:00 AM          0
4  1503960366  4/12/2016 12:04:00 AM          0

------minuteIntensitiesWide-------

,Id,ActivityHour,Intensity00,Intensity01,Intensity02,Intensity03,Intensity04,Intensity05,Intensity06,Intensity07,...,Intensity50,Intensity51,Intensity52,Intensity53,Intensity54,Intensity55,Intensity56,Intensity57,Intensity58,Intensity59
0,1503960366,4/13/2016 12:00:00 AM,1,1,0,0,0,1,0,1,...,0,1,1,0,1,1,0,0,0,0
1,1503960366,4/13/2016 1:00:00 AM,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1503960366,4/13/2016 2:00:00 AM,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1503960366,4/13/2016 3:00:00 AM,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1503960366,4/13/2016 4:00:00 AM,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

------minuteMETsNarrow-------

           Id         ActivityMinute  METs
0  1503960366  4/12/2016 12:00:00 AM    10
1  1503960366  4/12/2016 12:01:00 AM    10
2  1503960366  4/12/2016 12:02:00 AM    10
3  1503960366  4/12/2016 12:03:00 AM    10
4  1503960366  4/12/2016 12:04:00 AM    10

------minuteSleep-------

           Id                  date  value        logId
0  1503960366  4/12/2016 2:47:30 AM      3  11380564589
1  1503960366  4/12/2016 2:48:30 AM      2  11380564589
2  1503960366  4/12/2016 2:49:30 AM      1  11380564589
3  1503960366  4/12/2016 2:50:30 AM      1  11380564589
4  1503960366  4/12/2016 2:51:30 AM      1  11380564589

------minuteStepsNarrow-------

           Id         ActivityMinute  Steps
0  1503960366  4/12/2016 12:00:00 AM      0
1  1503960366  4/12/2016 12:01:00 AM      0
2  1503960366  4/12/2016 12:02:00 AM      0
3  1503960366  4/12/2016 12:03:00 AM      0
4  1503960366  4/12/2016 12:04:00 AM      0

------minuteStepsWide-------

,Id,ActivityHour,Steps00,Steps01,Steps02,Steps03,Steps04,Steps05,Steps06,Steps07,...,Steps50,Steps51,Steps52,Steps53,Steps54,Steps55,Steps56,Steps57,Steps58,Steps59
0,1503960366,4/13/2016 12:00:00 AM,4,16,0,0,0,9,0,17,...,0,9,8,0,20,1,0,0,0,0
1,1503960366,4/13/2016 1:00:00 AM,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1503960366,4/13/2016 2:00:00 AM,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1503960366,4/13/2016 3:00:00 AM,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1503960366,4/13/2016 4:00:00 AM,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

========INFO===========

------heartrate_seconds-------

           Id                  Time  Value
0  2022484408  4/12/2016 7:21:00 AM     97
1  2022484408  4/12/2016 7:21:05 AM    102
2  2022484408  4/12/2016 7:21:10 AM    105
3  2022484408  4/12/2016 7:21:20 AM    103
4  2022484408  4/12/2016 7:21:25 AM    101

------sleepDay-------

,Id,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
0,1503960366,4/12/2016 12:00:00 AM,1,327,346
1,1503960366,4/13/2016 12:00:00 AM,2,384,407
2,1503960366,4/15/2016 12:00:00 AM,1,412,442
3,1503960366,4/16/2016 12:00:00 AM,2,340,367
4,1503960366,4/17/2016 12:00:00 AM,1,700,712

------weightLogInfo-------

,Id,Date,WeightKg,WeightPounds,Fat,BMI,IsManualReport,LogId
0,1503960366,5/2/2016 11:59:59 PM,52.599998,115.963147,22.0,22.650000,True,1462233599000
1,1503960366,5/3/2016 11:59:59 PM,52.599998,115.963147,NaN,22.650000,True,1462319999000
2,1927972279,4/13/2016 1:08:52 AM,133.500000,294.317120,NaN,47.540001,False,1460509732000
3,2873212765,4/21/2016 11:59:59 PM,56.700001,125.002104,NaN,21.450001,True,1461283199000
4,2873212765,5/12/2016 11:59:59 PM,57.299999,126.324875,NaN,21.690001,True,1463097599000

In [35]:
for group, frame in data.items() :
    print(f"\n========{group.upper()}===========")
    for name, df in frame.items(): 
        print(f"\n------{name}-------")
        display(df.isnull().sum())
        print("\n Duplicates =")
        display(df.duplicated().sum())

========DAILY===========

------dailyActivity-------

Id                          0
ActivityDate                0
TotalSteps                  0
TotalDistance               0
TrackerDistance             0
LoggedActivitiesDistance    0
VeryActiveDistance          0
ModeratelyActiveDistance    0
LightActiveDistance         0
SedentaryActiveDistance     0
VeryActiveMinutes           0
FairlyActiveMinutes         0
LightlyActiveMinutes        0
SedentaryMinutes            0
Calories                    0
dtype: int64

 Duplicates =

np.int64(0)

------dailyCalories-------

Id             0
ActivityDay    0
Calories       0
dtype: int64

 Duplicates =

np.int64(0)

------dailyIntensities-------

Id                          0
ActivityDay                 0
SedentaryMinutes            0
LightlyActiveMinutes        0
FairlyActiveMinutes         0
VeryActiveMinutes           0
SedentaryActiveDistance     0
LightActiveDistance         0
ModeratelyActiveDistance    0
VeryActiveDistance          0
dtype: int64

 Duplicates =

np.int64(0)

------dailySteps-------

Id             0
ActivityDay    0
StepTotal      0
dtype: int64

 Duplicates =

np.int64(0)

========HOURLY===========

------hourlyCalories-------

Id              0
ActivityHour    0
Calories        0
dtype: int64

 Duplicates =

np.int64(0)

------hourlyIntensities-------

Id                  0
ActivityHour        0
TotalIntensity      0
AverageIntensity    0
dtype: int64

 Duplicates =

np.int64(0)

------hourlySteps-------

Id              0
ActivityHour    0
StepTotal       0
dtype: int64

 Duplicates =

np.int64(0)

========MINUTE===========

------minuteCaloriesNarrow-------

Id                0
ActivityMinute    0
Calories          0
dtype: int64

 Duplicates =

np.int64(0)

------minuteCaloriesWide-------

Id              0
ActivityHour    0
Calories00      0
Calories01      0
Calories02      0
               ..
Calories55      0
Calories56      0
Calories57      0
Calories58      0
Calories59      0
Length: 62, dtype: int64

 Duplicates =

np.int64(0)

------minuteIntensitiesNarrow-------

Id                0
ActivityMinute    0
Intensity         0
dtype: int64

 Duplicates =

np.int64(0)

------minuteIntensitiesWide-------

Id              0
ActivityHour    0
Intensity00     0
Intensity01     0
Intensity02     0
               ..
Intensity55     0
Intensity56     0
Intensity57     0
Intensity58     0
Intensity59     0
Length: 62, dtype: int64

 Duplicates =

np.int64(0)

------minuteMETsNarrow-------

Id                0
ActivityMinute    0
METs              0
dtype: int64

 Duplicates =

np.int64(0)

------minuteSleep-------

Id       0
date     0
value    0
logId    0
dtype: int64

 Duplicates =

np.int64(543)

------minuteStepsNarrow-------

Id                0
ActivityMinute    0
Steps             0
dtype: int64

 Duplicates =

np.int64(0)

------minuteStepsWide-------

Id              0
ActivityHour    0
Steps00         0
Steps01         0
Steps02         0
               ..
Steps55         0
Steps56         0
Steps57         0
Steps58         0
Steps59         0
Length: 62, dtype: int64

 Duplicates =

np.int64(0)

========INFO===========

------heartrate_seconds-------

Id       0
Time     0
Value    0
dtype: int64

 Duplicates =

np.int64(0)

------sleepDay-------

Id                    0
SleepDay              0
TotalSleepRecords     0
TotalMinutesAsleep    0
TotalTimeInBed        0
dtype: int64

 Duplicates =

np.int64(3)

------weightLogInfo-------

Id                 0
Date               0
WeightKg           0
WeightPounds       0
Fat               65
BMI                0
IsManualReport     0
LogId              0
dtype: int64

 Duplicates =

np.int64(0)