# Bellabeat Project 🏃‍♀️

## Import Libraries 📥

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

## Import and Read Data 📥📚

In [2]:
file_groups = {
    "daily": ["dailyActivity_merged.csv", "dailyCalories_merged.csv", "dailyIntensities_merged.csv", "dailySteps_merged.csv"],
    "hourly": ["hourlyCalories_merged.csv", "hourlyIntensities_merged.csv", "hourlySteps_merged.csv"],
    "minute": ["minuteCaloriesNarrow_merged.csv", "minuteCaloriesWide_merged.csv", "minuteIntensitiesNarrow_merged.csv", "minuteIntensitiesWide_merged.csv", "minuteMETsNarrow_merged.csv", "minuteSleep_merged.csv", "minuteStepsNarrow_merged.csv", "minuteStepsWide_merged.csv"],
    "info": ["heartrate_seconds_merged.csv", "sleepDay_merged.csv", "weightLogInfo_merged.csv"]
}

data = {}
for group, files in file_groups.items():
    data[group] = {
    f.replace("_merged.csv", ""): pd.read_csv(os.path.join('data/mturkfitbit_export_4.12.16-5.12.16/Fitabase data 4.12.16-5.12.16', f))
    for f in files
    }

## Checking Data Frames 👀

In [3]:
for group, frame in data.items() :
    print(f"\n========{group.upper()}===========")
    for name, df in frame.items(): 
        print(f"\n------{name}-------")
        display(df.head())

========DAILY===========

------dailyActivity-------

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,4/12/2016,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,25,13,328,728,1985
1,1503960366,4/13/2016,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,21,19,217,776,1797
2,1503960366,4/14/2016,10460,6.74,6.74,0.0,2.44,0.40,3.91,0.0,30,11,181,1218,1776
3,1503960366,4/15/2016,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.0,29,34,209,726,1745
4,1503960366,4/16/2016,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.0,36,10,221,773,1863

------dailyCalories-------

           Id ActivityDay  Calories
0  1503960366   4/12/2016      1985
1  1503960366   4/13/2016      1797
2  1503960366   4/14/2016      1776
3  1503960366   4/15/2016      1745
4  1503960366   4/16/2016      1863

------dailyIntensities-------

,Id,ActivityDay,SedentaryMinutes,LightlyActiveMinutes,FairlyActiveMinutes,VeryActiveMinutes,SedentaryActiveDistance,LightActiveDistance,ModeratelyActiveDistance,VeryActiveDistance
0,1503960366,4/12/2016,728,328,13,25,0.0,6.06,0.55,1.88
1,1503960366,4/13/2016,776,217,19,21,0.0,4.71,0.69,1.57
2,1503960366,4/14/2016,1218,181,11,30,0.0,3.91,0.40,2.44
3,1503960366,4/15/2016,726,209,34,29,0.0,2.83,1.26,2.14
4,1503960366,4/16/2016,773,221,10,36,0.0,5.04,0.41,2.71

------dailySteps-------

           Id ActivityDay  StepTotal
0  1503960366   4/12/2016      13162
1  1503960366   4/13/2016      10735
2  1503960366   4/14/2016      10460
3  1503960366   4/15/2016       9762
4  1503960366   4/16/2016      12669

========HOURLY===========

------hourlyCalories-------

           Id           ActivityHour  Calories
0  1503960366  4/12/2016 12:00:00 AM        81
1  1503960366   4/12/2016 1:00:00 AM        61
2  1503960366   4/12/2016 2:00:00 AM        59
3  1503960366   4/12/2016 3:00:00 AM        47
4  1503960366   4/12/2016 4:00:00 AM        48

------hourlyIntensities-------

           Id           ActivityHour  TotalIntensity  AverageIntensity
0  1503960366  4/12/2016 12:00:00 AM              20          0.333333
1  1503960366   4/12/2016 1:00:00 AM               8          0.133333
2  1503960366   4/12/2016 2:00:00 AM               7          0.116667
3  1503960366   4/12/2016 3:00:00 AM               0          0.000000
4  1503960366   4/12/2016 4:00:00 AM               0          0.000000

------hourlySteps-------

           Id           ActivityHour  StepTotal
0  1503960366  4/12/2016 12:00:00 AM        373
1  1503960366   4/12/2016 1:00:00 AM        160
2  1503960366   4/12/2016 2:00:00 AM        151
3  1503960366   4/12/2016 3:00:00 AM          0
4  1503960366   4/12/2016 4:00:00 AM          0

========MINUTE===========

------minuteCaloriesNarrow-------

           Id         ActivityMinute  Calories
0  1503960366  4/12/2016 12:00:00 AM    0.7865
1  1503960366  4/12/2016 12:01:00 AM    0.7865
2  1503960366  4/12/2016 12:02:00 AM    0.7865
3  1503960366  4/12/2016 12:03:00 AM    0.7865
4  1503960366  4/12/2016 12:04:00 AM    0.7865

------minuteCaloriesWide-------

,Id,ActivityHour,Calories00,Calories01,Calories02,Calories03,Calories04,Calories05,Calories06,Calories07,...,Calories50,Calories51,Calories52,Calories53,Calories54,Calories55,Calories56,Calories57,Calories58,Calories59
0,1503960366,4/13/2016 12:00:00 AM,1.8876,2.2022,0.9438,0.9438,0.9438,2.0449,0.9438,2.2022,...,0.9438,2.0449,2.0449,0.9438,2.3595,1.8876,0.9438,0.9438,0.9438,0.9438
1,1503960366,4/13/2016 1:00:00 AM,0.7865,0.7865,0.7865,0.7865,0.9438,0.9438,0.9438,0.7865,...,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865
2,1503960366,4/13/2016 2:00:00 AM,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,...,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865
3,1503960366,4/13/2016 3:00:00 AM,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,...,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865
4,1503960366,4/13/2016 4:00:00 AM,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,...,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865,0.7865

------minuteIntensitiesNarrow-------

           Id         ActivityMinute  Intensity
0  1503960366  4/12/2016 12:00:00 AM          0
1  1503960366  4/12/2016 12:01:00 AM          0
2  1503960366  4/12/2016 12:02:00 AM          0
3  1503960366  4/12/2016 12:03:00 AM          0
4  1503960366  4/12/2016 12:04:00 AM          0

------minuteIntensitiesWide-------

,Id,ActivityHour,Intensity00,Intensity01,Intensity02,Intensity03,Intensity04,Intensity05,Intensity06,Intensity07,...,Intensity50,Intensity51,Intensity52,Intensity53,Intensity54,Intensity55,Intensity56,Intensity57,Intensity58,Intensity59
0,1503960366,4/13/2016 12:00:00 AM,1,1,0,0,0,1,0,1,...,0,1,1,0,1,1,0,0,0,0
1,1503960366,4/13/2016 1:00:00 AM,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1503960366,4/13/2016 2:00:00 AM,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1503960366,4/13/2016 3:00:00 AM,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1503960366,4/13/2016 4:00:00 AM,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

------minuteMETsNarrow-------

           Id         ActivityMinute  METs
0  1503960366  4/12/2016 12:00:00 AM    10
1  1503960366  4/12/2016 12:01:00 AM    10
2  1503960366  4/12/2016 12:02:00 AM    10
3  1503960366  4/12/2016 12:03:00 AM    10
4  1503960366  4/12/2016 12:04:00 AM    10

------minuteSleep-------

           Id                  date  value        logId
0  1503960366  4/12/2016 2:47:30 AM      3  11380564589
1  1503960366  4/12/2016 2:48:30 AM      2  11380564589
2  1503960366  4/12/2016 2:49:30 AM      1  11380564589
3  1503960366  4/12/2016 2:50:30 AM      1  11380564589
4  1503960366  4/12/2016 2:51:30 AM      1  11380564589

------minuteStepsNarrow-------

           Id         ActivityMinute  Steps
0  1503960366  4/12/2016 12:00:00 AM      0
1  1503960366  4/12/2016 12:01:00 AM      0
2  1503960366  4/12/2016 12:02:00 AM      0
3  1503960366  4/12/2016 12:03:00 AM      0
4  1503960366  4/12/2016 12:04:00 AM      0

------minuteStepsWide-------

,Id,ActivityHour,Steps00,Steps01,Steps02,Steps03,Steps04,Steps05,Steps06,Steps07,...,Steps50,Steps51,Steps52,Steps53,Steps54,Steps55,Steps56,Steps57,Steps58,Steps59
0,1503960366,4/13/2016 12:00:00 AM,4,16,0,0,0,9,0,17,...,0,9,8,0,20,1,0,0,0,0
1,1503960366,4/13/2016 1:00:00 AM,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1503960366,4/13/2016 2:00:00 AM,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1503960366,4/13/2016 3:00:00 AM,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1503960366,4/13/2016 4:00:00 AM,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

========INFO===========

------heartrate_seconds-------

           Id                  Time  Value
0  2022484408  4/12/2016 7:21:00 AM     97
1  2022484408  4/12/2016 7:21:05 AM    102
2  2022484408  4/12/2016 7:21:10 AM    105
3  2022484408  4/12/2016 7:21:20 AM    103
4  2022484408  4/12/2016 7:21:25 AM    101

------sleepDay-------

,Id,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
0,1503960366,4/12/2016 12:00:00 AM,1,327,346
1,1503960366,4/13/2016 12:00:00 AM,2,384,407
2,1503960366,4/15/2016 12:00:00 AM,1,412,442
3,1503960366,4/16/2016 12:00:00 AM,2,340,367
4,1503960366,4/17/2016 12:00:00 AM,1,700,712

------weightLogInfo-------

,Id,Date,WeightKg,WeightPounds,Fat,BMI,IsManualReport,LogId
0,1503960366,5/2/2016 11:59:59 PM,52.599998,115.963147,22.0,22.650000,True,1462233599000
1,1503960366,5/3/2016 11:59:59 PM,52.599998,115.963147,NaN,22.650000,True,1462319999000
2,1927972279,4/13/2016 1:08:52 AM,133.500000,294.317120,NaN,47.540001,False,1460509732000
3,2873212765,4/21/2016 11:59:59 PM,56.700001,125.002104,NaN,21.450001,True,1461283199000
4,2873212765,5/12/2016 11:59:59 PM,57.299999,126.324875,NaN,21.690001,True,1463097599000

## Cleaning 🧼🧹

In [4]:
# Running many functions to comb through and check for any dirty data.

for group, frame in data.items() :
    print(f"\n========{group.upper()}===========")
    for name, df in frame.items(): 
        print(f"\n------{name}-------")
        display(df.isnull().sum()) # Here I am lookng for null values
        print("\n Duplicates: ")
        display(df.duplicated().sum()) # Here I am looking for duplicates
        print("\n Info: ")
        display(df.describe()) # Here I am checking for outlires and misinput values (ex. -1)

========DAILY===========

------dailyActivity-------

Id                          0
ActivityDate                0
TotalSteps                  0
TotalDistance               0
TrackerDistance             0
LoggedActivitiesDistance    0
VeryActiveDistance          0
ModeratelyActiveDistance    0
LightActiveDistance         0
SedentaryActiveDistance     0
VeryActiveMinutes           0
FairlyActiveMinutes         0
LightlyActiveMinutes        0
SedentaryMinutes            0
Calories                    0
dtype: int64

 Duplicates:

np.int64(0)

 Info:

,Id,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
count,9.400000e+02,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000
mean,4.855407e+09,7637.910638,5.489702,5.475351,0.108171,1.502681,0.567543,3.340819,0.001606,21.164894,13.564894,192.812766,991.210638,2303.609574
std,2.424805e+09,5087.150742,3.924606,3.907276,0.619897,2.658941,0.883580,2.040655,0.007346,32.844803,19.987404,109.174700,301.267437,718.166862
min,1.503960e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.320127e+09,3789.750000,2.620000,2.620000,0.000000,0.000000,0.000000,1.945000,0.000000,0.000000,0.000000,127.000000,729.750000,1828.500000
50%,4.445115e+09,7405.500000,5.245000,5.245000,0.000000,0.210000,0.240000,3.365000,0.000000,4.000000,6.000000,199.000000,1057.500000,2134.000000
75%,6.962181e+09,10727.000000,7.712500,7.710000,0.000000,2.052500,0.800000,4.782500,0.000000,32.000000,19.000000,264.000000,1229.500000,2793.250000
max,8.877689e+09,36019.000000,28.030001,28.030001,4.942142,21.920000,6.480000,10.710000,0.110000,210.000000,143.000000,518.000000,1440.000000,4900.000000

------dailyCalories-------

Id             0
ActivityDay    0
Calories       0
dtype: int64

 Duplicates:

np.int64(0)

 Info:

                 Id     Calories
count  9.400000e+02   940.000000
mean   4.855407e+09  2303.609574
std    2.424805e+09   718.166862
min    1.503960e+09     0.000000
25%    2.320127e+09  1828.500000
50%    4.445115e+09  2134.000000
75%    6.962181e+09  2793.250000
max    8.877689e+09  4900.000000

------dailyIntensities-------

Id                          0
ActivityDay                 0
SedentaryMinutes            0
LightlyActiveMinutes        0
FairlyActiveMinutes         0
VeryActiveMinutes           0
SedentaryActiveDistance     0
LightActiveDistance         0
ModeratelyActiveDistance    0
VeryActiveDistance          0
dtype: int64

 Duplicates:

np.int64(0)

 Info:

,Id,SedentaryMinutes,LightlyActiveMinutes,FairlyActiveMinutes,VeryActiveMinutes,SedentaryActiveDistance,LightActiveDistance,ModeratelyActiveDistance,VeryActiveDistance
count,9.400000e+02,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000
mean,4.855407e+09,991.210638,192.812766,13.564894,21.164894,0.001606,3.340819,0.567543,1.502681
std,2.424805e+09,301.267437,109.174700,19.987404,32.844803,0.007346,2.040655,0.883580,2.658941
min,1.503960e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.320127e+09,729.750000,127.000000,0.000000,0.000000,0.000000,1.945000,0.000000,0.000000
50%,4.445115e+09,1057.500000,199.000000,6.000000,4.000000,0.000000,3.365000,0.240000,0.210000
75%,6.962181e+09,1229.500000,264.000000,19.000000,32.000000,0.000000,4.782500,0.800000,2.052500
max,8.877689e+09,1440.000000,518.000000,143.000000,210.000000,0.110000,10.710000,6.480000,21.920000

------dailySteps-------

Id             0
ActivityDay    0
StepTotal      0
dtype: int64

 Duplicates:

np.int64(0)

 Info:

                 Id     StepTotal
count  9.400000e+02    940.000000
mean   4.855407e+09   7637.910638
std    2.424805e+09   5087.150742
min    1.503960e+09      0.000000
25%    2.320127e+09   3789.750000
50%    4.445115e+09   7405.500000
75%    6.962181e+09  10727.000000
max    8.877689e+09  36019.000000

========HOURLY===========

------hourlyCalories-------

Id              0
ActivityHour    0
Calories        0
dtype: int64

 Duplicates:

np.int64(0)

 Info:

                 Id      Calories
count  2.209900e+04  22099.000000
mean   4.848235e+09     97.386760
std    2.422500e+09     60.702622
min    1.503960e+09     42.000000
25%    2.320127e+09     63.000000
50%    4.445115e+09     83.000000
75%    6.962181e+09    108.000000
max    8.877689e+09    948.000000

------hourlyIntensities-------

Id                  0
ActivityHour        0
TotalIntensity      0
AverageIntensity    0
dtype: int64

 Duplicates:

np.int64(0)

 Info:

                 Id  TotalIntensity  AverageIntensity
count  2.209900e+04    22099.000000      22099.000000
mean   4.848235e+09       12.035341          0.200589
std    2.422500e+09       21.133110          0.352219
min    1.503960e+09        0.000000          0.000000
25%    2.320127e+09        0.000000          0.000000
50%    4.445115e+09        3.000000          0.050000
75%    6.962181e+09       16.000000          0.266667
max    8.877689e+09      180.000000          3.000000

------hourlySteps-------

Id              0
ActivityHour    0
StepTotal       0
dtype: int64

 Duplicates:

np.int64(0)

 Info:

                 Id     StepTotal
count  2.209900e+04  22099.000000
mean   4.848235e+09    320.166342
std    2.422500e+09    690.384228
min    1.503960e+09      0.000000
25%    2.320127e+09      0.000000
50%    4.445115e+09     40.000000
75%    6.962181e+09    357.000000
max    8.877689e+09  10554.000000

========MINUTE===========

------minuteCaloriesNarrow-------

Id                0
ActivityMinute    0
Calories          0
dtype: int64

 Duplicates:

np.int64(0)

 Info:

                 Id      Calories
count  1.325580e+06  1.325580e+06
mean   4.847898e+09  1.623130e+00
std    2.422313e+09  1.410447e+00
min    1.503960e+09  0.000000e+00
25%    2.320127e+09  9.357000e-01
50%    4.445115e+09  1.217600e+00
75%    6.962181e+09  1.432700e+00
max    8.877689e+09  1.974995e+01

------minuteCaloriesWide-------

Id              0
ActivityHour    0
Calories00      0
Calories01      0
Calories02      0
               ..
Calories55      0
Calories56      0
Calories57      0
Calories58      0
Calories59      0
Length: 62, dtype: int64

 Duplicates:

np.int64(0)

 Info:

,Id,Calories00,Calories01,Calories02,Calories03,Calories04,Calories05,Calories06,Calories07,Calories08,...,Calories50,Calories51,Calories52,Calories53,Calories54,Calories55,Calories56,Calories57,Calories58,Calories59
count,2.164500e+04,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,...,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000
mean,4.836965e+09,1.622629,1.626377,1.637824,1.635515,1.637997,1.638306,1.639910,1.629520,1.623686,...,1.623665,1.613643,1.620958,1.618227,1.621229,1.615972,1.608714,1.612657,1.611715,1.612110
std,2.424088e+09,1.398418,1.395083,1.408828,1.419590,1.433532,1.438253,1.435465,1.424092,1.411596,...,1.407171,1.395206,1.407914,1.400498,1.408974,1.392530,1.376827,1.369097,1.374954,1.373888
min,1.503960e+09,0.702700,0.702700,0.702700,0.702700,0.702700,0.702700,0.702700,0.702700,0.702700,...,0.702700,0.702700,0.702700,0.702700,0.702700,0.702700,0.702700,0.702700,0.702700,0.000000
25%,2.320127e+09,0.935700,0.935700,0.937680,0.935700,0.935700,0.935700,0.935700,0.935700,0.935700,...,0.935700,0.935700,0.935700,0.935700,0.935700,0.935700,0.935700,0.935700,0.935700,0.935700
50%,4.445115e+09,1.217600,1.217600,1.220400,1.218500,1.218500,1.218500,1.218500,1.217600,1.217600,...,1.217600,1.217600,1.217600,1.217600,1.217600,1.217600,1.217600,1.217600,1.217600,1.217600
75%,6.962181e+09,1.432700,1.432700,1.432700,1.432700,1.432700,1.432700,1.432700,1.432700,1.432700,...,1.432700,1.432700,1.432700,1.432700,1.432700,1.432700,1.432700,1.432700,1.432700,1.432700
max,8.877689e+09,19.727337,19.727337,19.727337,19.727337,19.727337,19.727337,19.727337,19.727337,19.727337,...,19.749947,19.749947,19.749947,19.749947,19.749947,19.749947,19.727337,19.727337,19.727337,19.727337

------minuteIntensitiesNarrow-------

Id                0
ActivityMinute    0
Intensity         0
dtype: int64

 Duplicates:

np.int64(0)

 Info:

                 Id     Intensity
count  1.325580e+06  1.325580e+06
mean   4.847898e+09  2.005937e-01
std    2.422313e+09  5.190227e-01
min    1.503960e+09  0.000000e+00
25%    2.320127e+09  0.000000e+00
50%    4.445115e+09  0.000000e+00
75%    6.962181e+09  0.000000e+00
max    8.877689e+09  3.000000e+00

------minuteIntensitiesWide-------

Id              0
ActivityHour    0
Intensity00     0
Intensity01     0
Intensity02     0
               ..
Intensity55     0
Intensity56     0
Intensity57     0
Intensity58     0
Intensity59     0
Length: 62, dtype: int64

 Duplicates:

np.int64(0)

 Info:

,Id,Intensity00,Intensity01,Intensity02,Intensity03,Intensity04,Intensity05,Intensity06,Intensity07,Intensity08,...,Intensity50,Intensity51,Intensity52,Intensity53,Intensity54,Intensity55,Intensity56,Intensity57,Intensity58,Intensity59
count,2.164500e+04,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,...,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000
mean,4.836965e+09,0.199723,0.203326,0.208177,0.203835,0.205082,0.204897,0.206560,0.201894,0.202310,...,0.201016,0.195796,0.198337,0.199399,0.200139,0.198753,0.195565,0.199122,0.198244,0.195426
std,2.424088e+09,0.509819,0.515432,0.521394,0.518137,0.521956,0.521054,0.523053,0.519074,0.522594,...,0.514814,0.510299,0.511264,0.513331,0.512142,0.511238,0.506435,0.511907,0.510124,0.503423
min,1.503960e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.320127e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4.445115e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6.962181e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8.877689e+09,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,...,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000

------minuteMETsNarrow-------

Id                0
ActivityMinute    0
METs              0
dtype: int64

 Duplicates:

np.int64(0)

 Info:

                 Id          METs
count  1.325580e+06  1.325580e+06
mean   4.847898e+09  1.469001e+01
std    2.422313e+09  1.205541e+01
min    1.503960e+09  0.000000e+00
25%    2.320127e+09  1.000000e+01
50%    4.445115e+09  1.000000e+01
75%    6.962181e+09  1.100000e+01
max    8.877689e+09  1.570000e+02

------minuteSleep-------

Id       0
date     0
value    0
logId    0
dtype: int64

 Duplicates:

np.int64(543)

 Info:

                 Id          value         logId
count  1.885210e+05  188521.000000  1.885210e+05
mean   4.996595e+09       1.095793  1.149611e+10
std    2.066950e+09       0.328673  6.822863e+07
min    1.503960e+09       1.000000  1.137223e+10
25%    3.977334e+09       1.000000  1.143931e+10
50%    4.702922e+09       1.000000  1.150114e+10
75%    6.962181e+09       1.000000  1.155253e+10
max    8.792010e+09       3.000000  1.161625e+10

------minuteStepsNarrow-------

Id                0
ActivityMinute    0
Steps             0
dtype: int64

 Duplicates:

np.int64(0)

 Info:

                 Id         Steps
count  1.325580e+06  1.325580e+06
mean   4.847898e+09  5.336192e+00
std    2.422313e+09  1.812830e+01
min    1.503960e+09  0.000000e+00
25%    2.320127e+09  0.000000e+00
50%    4.445115e+09  0.000000e+00
75%    6.962181e+09  0.000000e+00
max    8.877689e+09  2.200000e+02

------minuteStepsWide-------

Id              0
ActivityHour    0
Steps00         0
Steps01         0
Steps02         0
               ..
Steps55         0
Steps56         0
Steps57         0
Steps58         0
Steps59         0
Length: 62, dtype: int64

 Duplicates:

np.int64(0)

 Info:

,Id,Steps00,Steps01,Steps02,Steps03,Steps04,Steps05,Steps06,Steps07,Steps08,...,Steps50,Steps51,Steps52,Steps53,Steps54,Steps55,Steps56,Steps57,Steps58,Steps59
count,2.164500e+04,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.00000,...,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000,21645.000000
mean,4.836965e+09,5.304366,5.335412,5.531439,5.469439,5.461862,5.590252,5.559483,5.412474,5.35879,...,5.329175,5.194456,5.225595,5.145484,5.223654,5.281220,5.179533,5.251836,5.143636,5.288935
std,2.424088e+09,17.783331,17.678358,18.079791,18.106414,18.288469,18.565165,18.484912,18.335665,18.20523,...,17.870527,17.601857,17.618497,17.570195,17.684634,17.828413,17.569268,17.686583,17.427494,17.721454
min,1.503960e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.320127e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4.445115e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6.962181e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8.877689e+09,186.000000,180.000000,182.000000,182.000000,181.000000,180.000000,181.000000,183.000000,180.00000,...,182.000000,181.000000,181.000000,181.000000,184.000000,181.000000,182.000000,182.000000,180.000000,189.000000

========INFO===========

------heartrate_seconds-------

Id       0
Time     0
Value    0
dtype: int64

 Duplicates:

np.int64(0)

 Info:

                 Id         Value
count  2.483658e+06  2.483658e+06
mean   5.513765e+09  7.732842e+01
std    1.950224e+09  1.940450e+01
min    2.022484e+09  3.600000e+01
25%    4.388162e+09  6.300000e+01
50%    5.553957e+09  7.300000e+01
75%    6.962181e+09  8.800000e+01
max    8.877689e+09  2.030000e+02

------sleepDay-------

Id                    0
SleepDay              0
TotalSleepRecords     0
TotalMinutesAsleep    0
TotalTimeInBed        0
dtype: int64

 Duplicates:

np.int64(3)

 Info:

                 Id  TotalSleepRecords  TotalMinutesAsleep  TotalTimeInBed
count  4.130000e+02         413.000000          413.000000      413.000000
mean   5.000979e+09           1.118644          419.467312      458.639225
std    2.060360e+09           0.345521          118.344679      127.101607
min    1.503960e+09           1.000000           58.000000       61.000000
25%    3.977334e+09           1.000000          361.000000      403.000000
50%    4.702922e+09           1.000000          433.000000      463.000000
75%    6.962181e+09           1.000000          490.000000      526.000000
max    8.792010e+09           3.000000          796.000000      961.000000

------weightLogInfo-------

Id                 0
Date               0
WeightKg           0
WeightPounds       0
Fat               65
BMI                0
IsManualReport     0
LogId              0
dtype: int64

 Duplicates:

np.int64(0)

 Info:

,Id,WeightKg,WeightPounds,Fat,BMI,LogId
count,6.700000e+01,67.000000,67.000000,2.00000,67.000000,6.700000e+01
mean,7.009282e+09,72.035821,158.811801,23.50000,25.185224,1.461772e+12
std,1.950322e+09,13.923206,30.695415,2.12132,3.066963,7.829948e+08
min,1.503960e+09,52.599998,115.963147,22.00000,21.450001,1.460444e+12
25%,6.962181e+09,61.400002,135.363832,22.75000,23.959999,1.461079e+12
50%,6.962181e+09,62.500000,137.788914,23.50000,24.389999,1.461802e+12
75%,8.877689e+09,85.049999,187.503152,24.25000,25.559999,1.462375e+12
max,8.877689e+09,133.500000,294.317120,25.00000,47.540001,1.463098e+12

### Found 65 of 67 entries missing 🚫 in column 'Fat'

In [5]:
weight_df = data['info']['weightLogInfo'].copy()
weight_df[weight_df['Fat'].notna()]

,Id,Date,WeightKg,WeightPounds,Fat,BMI,IsManualReport,LogId
0,1503960366,5/2/2016 11:59:59 PM,52.599998,115.963147,22.0,22.650000,True,1462233599000
5,4319703577,4/17/2016 11:59:59 PM,72.400002,159.614681,25.0,27.450001,True,1460937599000

### Deleting 'Fat' column ❌🗑

In [18]:
# deleting the fat column because it has a lot of null values and is not needed for our analysis.
data['info']['weightLogInfo'] = data['info']['weightLogInfo'].drop(columns = 'Fat')

KeyError: "['Fat'] not found in axis"

In [17]:
# Checking data frame after deleting column
display(data['info']['weightLogInfo'].head())

,Id,Date,WeightKg,WeightPounds,BMI,IsManualReport,LogId
0,1503960366,5/2/2016 11:59:59 PM,52.599998,115.963147,22.650000,True,1462233599000
1,1503960366,5/3/2016 11:59:59 PM,52.599998,115.963147,22.650000,True,1462319999000
2,1927972279,4/13/2016 1:08:52 AM,133.500000,294.317120,47.540001,False,1460509732000
3,2873212765,4/21/2016 11:59:59 PM,56.700001,125.002104,21.450001,True,1461283199000
4,2873212765,5/12/2016 11:59:59 PM,57.299999,126.324875,21.690001,True,1463097599000

#### Double checking the data frame for null values

In [ ]:
# Checkig for null values
data['info']['weightLogInfo'].isna().sum()

Id                0
Date              0
WeightKg          0
WeightPounds      0
BMI               0
IsManualReport    0
LogId             0
dtype: int64